# 目标系统环境
set(CMAKE_SYSTEM_NAME raspberrypi)
set(CMAKE_SYSTEM_VERSION 4.19.97-v7l+)
# 交叉编译器架构
set(CMAKE_LIBRARY_ARCHITECTURE $ENV{ARM_COMPILER_ARCH} CACHE STRING "交叉编译器架构")
# 系统根目录
set(ARM_SYSROOT_DIR $ENV{RASP_SYSROOT_DIR})
# 交叉编译器设置
set(CMAKE_CXX_COMPILER ${CMAKE_LIBRARY_ARCHITECTURE}-g++)
set(CMAKE_C_COMPILER ${CMAKE_LIBRARY_ARCHITECTURE}-gcc)
# 交叉编译器目标环境
set(CMAKE_FIND_ROOT_PATH ${ARM_SYSROOT_DIR} $ENV{ARM_COMPILER_PATH}/${CMAKE_LIBRARY_ARCHITECTURE})
# CMake 系统文件目录
set(CMAKE_SYSROOT ${ARM_SYSROOT_DIR})

message(STATUS "SYSROOT ${CMAKE_SYSROOT}")
message(STATUS "FIND_ROOT_PATH ${CMAKE_FIND_ROOT_PATH}")
message(STATUS "LIBRARY_ARCHITECTURE ${CMAKE_LIBRARY_ARCHITECTURE}")

# 在宿主机和目标环境内寻找应用程序
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM BOTH)

# 只在目标环境内寻找包含文件和库文件
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
